name = "cortex_m4f"
description = "cortex_m4f support"
version = "1.0.0"
website = "https://github.com/ohenley/cortex_m"
licenses = "Apache-2.0"
tags = ["embedded", "baremetal"]

authors = ["ohenley"]
maintainers = ["ohenley <olivier.henley@gmail.com>"]
maintainers-logins = ["ohenley"]

[[depends-on]]
cortex_m = "~1.0.0"